<div id="content">
    <div id="tabs">

        <!-- jQuery UI tabs -->
        <ul id="sortable">
        <?php $i = 0; foreach ($this->feeds as $feed) { ?>
            <li feed-url="<?php echo $feed['feed-url']; ?>" tab="<?php echo $i; ?>">
                <a href="#tabs-<?php echo $i++; ?>">
                <?php echo $feed['name']; ?>
                </a>
            </li>
        <?php } ?>
        </ul>
        <?php $i = 0; foreach ($this->feeds as $feed) { ?>
            <div id="tabs-<?php echo $i; ?>">    
                <table id="news-feed-container" class="table table-bordered">
                    
                    <!-- RSS Feed head, where title, description, picture, and menu buttons reside -->
                    <thead>
                        <tr>
                            <td class="feed-info">
                                <div class="feed-pic">
                                    <img src="<?php echo $feed['image']; ?>" alt="">
                                </div>
                                <div class="feed-description">
                                    <a href="<?php echo $feed['link']; ?>" target="_blank">
                                        <h3><?php echo $feed['title']; ?></h3>
                                    </a>
                                    <?php echo $feed['description']; ?>         
                                </div>
                                <div class="btn-group-vertical">
                                    <button type="button" class="btn feed-refresh">Refresh feed</button>
                                    <button type="button" class="btn feed-edit">
                                        <a href="/index/edit-feed?id=<?php echo $feed['id']; ?>">Edit feed</a>
                                    </button>
                                    <button type="button" class="btn feed-delete">
                                        <a href="/index/delete?id=<?php echo $feed['id']; ?>" onclick="return confirm('Are you sure you want to delete this feed?')">Delete feed</a>
                                    </button>
                                </div>
                            </td>
                        </tr>
                        <tr>
                            <td>
                                <input type="text" class="filter-search" tab="<?php echo $i; ?>" placeholder="Enter a word or phrase to filter your results">
                            </td>
                        </tr>
                    </thead>

                    <!-- Caching the creation and editing of the entries -->
                    <?php
                    $frontendOptions = array(
                       'lifetime' => $feed['ttl']
                    );
                     
                    $backendOptions = array('cache_dir' => '../data/cache/');
                     
                    $cache = Zend_Cache::factory('Output', 'File', $frontendOptions, $backendOptions);

                    $cacheName = str_replace(' ', '', ucwords($feed['name']));
                    if(!$cache->start($cacheName)) { ?>

                    <tbody class="entries" tab="<?php echo $i++; ?>">
                    <?php foreach ($feed['entries'] as $entry) { ?>
                        <?php echo $entry; ?>
                    <?php } ?>
                    </tbody>

                    <?php $cache->end();
                    } else { 
                        $i++;
                    } ?>
                </table>
            </div>
        <?php } ?>
    </div>
</div>